version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

    restart: unless-stopped

    volumes:
      - clinic_db_data:/var/lib/mysql

    networks:
      - clinic_network
      
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  

  app:
    build: .  #the Dockerfile in this directory
    ports:
      - "8080:8080"
    environment:                       #not localhost
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - clinic_network
    depends_on:
      mysql: #Wait for mysql to run first so i can connect to it
        condition: service_healthy
    restart: on-failure




volumes:
  clinic_db_data:

networks:
  clinic_network:
    driver: bridge