version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

    restart: unless-stopped

    volumes:
      - clinic_db_data:/var/lib/mysql

    networks:
      - clinic_network
      
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  

  app:
    build: .  #the Dockerfile in this directory
    ports:
      - "8080:8080"
    environment:                       #not localhost
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092



    networks:
      - clinic_network
    depends_on:
      mysql: #Wait for mysql to run first so i can connect to it
        condition: service_healthy
      rabbitmq:
        condition: service_started
      kafka:
        condition: service_started

    restart: on-failure


  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - clinic_network


  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"        # AMQP port
      - "15672:15672"      # Admin UI port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - clinic_network
  
  kafka:
    image: apache/kafka:latest
    ports:
    - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller    # Single node does both roles no zookeeeper
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092 # all IPs 9092 for clients
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092   # Spring connects using this
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 #Node we have id =1 and at 9093 controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1    # We only have 1 broker
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      
    networks:
    - clinic_network

  
  

  



volumes:
  clinic_db_data:

networks:
  clinic_network:
    driver: bridge