#only show warn in console not info ones

logging.level.root=WARN
spring.jpa.show-sql=true
# show info type messages from my code (for logging)
logging.level.com.example.clinicmvcspring=INFO
spring.security.user.name=devName

spring.security.user.password=1234

