spring.application.name=Clinic-MVC-Spring
# 1. The location of your database on your PC (port 3306)
# The part '?createDatabaseIfNotExist=true' tells Spring Boot to create "clinic_db" for you!
spring.datasource.url=jdbc:mysql://localhost:3306/hospitaldb?createDatabaseIfNotExist=false&serverTimezone=UTC


spring.datasource.username=root

spring.datasource.password=1234


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
